import turtle as trtl

drawer = trtl.Turtle()

drawer.penup()
drawer.goto(15,5)
drawer.pendown()
drawer.pencolor("darkorange1")
drawer.pensize(15)

drawer.fillcolor("darkorange1")
drawer.begin_fill()
drawer.left(90)
drawer.forward(500)
drawer.left(90)
drawer.forward(350)
drawer.left(90)
drawer.forward(500)
drawer.left(90)
drawer.forward(350)
drawer.end_fill()

drawer.penup()
drawer.goto(12,7)
drawer.pendown()
drawer.pencolor("blue")
drawer.left(90)
drawer.forward(490)
drawer.left(90)
drawer.forward(343)
drawer.left(90)
drawer.forward(489)
drawer.left(90)
drawer.forward(343)

drawer.pencolor("black")
drawer.pensize(10)
drawer.penup()
drawer.goto(-40,250)
drawer.pendown()
drawer.fillcolor("green")
drawer.begin_fill()
drawer.left(90)
drawer.forward(40)
drawer.left(90)
drawer.forward(100)
drawer.left(180)
drawer.forward(100)
drawer.left(90)
drawer.forward(40)
drawer.left(90)
drawer.forward(100)
drawer.right(90)
drawer.forward(60)
drawer.left(90)
drawer.forward(90)
drawer.left(90)
drawer.forward(139)
drawer.left(90)
drawer.forward(190)
drawer.end_fill()

drawer.penup()
drawer.goto(-175,340)
drawer.pendown()
drawer.pensize(5)
drawer.circle(15)

drawer.penup()
drawer.goto(-175,345)
drawer.pendown()
drawer.pencolor("white")
drawer.fillcolor("white")
drawer.begin_fill()
drawer.pensize(2)
drawer.circle(10)
drawer.end_fill()

drawer.penup()
drawer.goto(-175,350)
drawer.pendown()
drawer.pencolor("black")
drawer.fillcolor("black")
drawer.begin_fill()
drawer.circle(5)
drawer.end_fill()

wn = trtl.Screen()
wn.mainloop()